// Code generated by "stringer -type=Code -linecomment"; DO NOT EDIT.

package e

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ok-0]
	_ = x[UnknownError-1]
	_ = x[InvalidParams-2]
	_ = x[InvalidUrl-3]
	_ = x[UnavailableEngine-4]
	_ = x[FetchMediaInfoError-5]
	_ = x[DownloadMediaError-6]
}

const _Code_name = "okunknown errorparams is not validurl is not validengine is not availablefailed to fetch media infofailed to download media"

var _Code_index = [...]uint8{0, 2, 15, 34, 50, 73, 99, 123}

func (i Code) String() string {
	if i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
