# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from app.util.download_thread import GetVideoInfoThread
from app import kwargs
from app import mlog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 440)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/res/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.label_url = QtWidgets.QLabel(self.central_widget)
        self.label_url.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label_url.setObjectName("label_url")
        self.button_download = QtWidgets.QPushButton(self.central_widget)
        self.button_download.setGeometry(QtCore.QRect(410, 20, 61, 61))
        self.button_download.setStyleSheet("border-image: url(:/new/prefix1/res/download.png);\n"
                                           "")
        self.button_download.setText("")
        self.button_download.setObjectName("button_download")
        self.label_support_sites = QtWidgets.QLabel(self.central_widget)
        self.label_support_sites.setGeometry(QtCore.QRect(10, 100, 121, 31))
        self.label_support_sites.setObjectName("label_support_sites")
        self.text_edit_urls = QtWidgets.QTextEdit(self.central_widget)
        self.text_edit_urls.setEnabled(True)
        self.text_edit_urls.setGeometry(QtCore.QRect(10, 130, 480, 271))
        self.text_edit_urls.setReadOnly(True)
        self.text_edit_urls.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.text_edit_urls.setObjectName("text_edit_urls")
        self.urls_text_edit = QtWidgets.QTextEdit(self.central_widget)
        self.urls_text_edit.setGeometry(QtCore.QRect(60, 30, 321, 61))
        self.urls_text_edit.setObjectName("urls_text_edit")
        MainWindow.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 500, 19))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_settings = QtWidgets.QMenu(self.menu_bar)
        self.menu_settings.setObjectName("menu_settings")
        self.menu_help = QtWidgets.QMenu(self.menu_bar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setEnabled(True)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)
        self.action_file_path = QtWidgets.QAction(MainWindow)
        self.action_file_path.setObjectName("action_file_path")
        self.action_check_for_updates = QtWidgets.QAction(MainWindow)
        self.action_check_for_updates.setObjectName("action_check_for_updates")
        self.action_report_bugs = QtWidgets.QAction(MainWindow)
        self.action_report_bugs.setObjectName("action_report_bugs")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menu_settings.addAction(self.action_file_path)
        self.menu_help.addAction(self.action_report_bugs)
        self.menu_help.addAction(self.action_about)
        self.menu_bar.addAction(self.menu_settings.menuAction())
        self.menu_bar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouGet"))
        self.label_url.setText(_translate("MainWindow", "URL"))
        self.button_download.setStatusTip(_translate("MainWindow", "Here we go!"))
        self.label_support_sites.setText(_translate("MainWindow", "Supported Sites"))
        self.text_edit_urls.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                               "<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\"><thead>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Site</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">URL</span></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Videos?</span></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Images?</span></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Audios?</span></p></td></tr></thead>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">YouTube</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.youtube.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.youtube.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Twitter</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://twitter.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://twitter.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">VK</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://vk.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://vk.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Vine</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://vine.co/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://vine.co/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Vimeo</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://vimeo.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://vimeo.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Vidto</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://vidto.me/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://vidto.me/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Videomega</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://videomega.tv/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://videomega.tv/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Veoh</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.veoh.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.veoh.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Tumblr</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.tumblr.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.tumblr.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TED</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.ted.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.ted.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SoundCloud</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://soundcloud.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://soundcloud.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pinterest</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.pinterest.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.pinterest.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MusicPlayOn</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://en.musicplayon.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://en.musicplayon.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MTV81</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.mtv81.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.mtv81.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mixcloud</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.mixcloud.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.mixcloud.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Metacafe</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.metacafe.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.metacafe.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Magisto</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.magisto.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.magisto.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Khan Academy</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.khanacademy.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.khanacademy.org/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">JPopsuki TV</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.jpopsuki.tv/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.jpopsuki.tv/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Internet Archive</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://archive.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://archive.org/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Instagram</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://instagram.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://instagram.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">InfoQ</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.infoq.com/presentations/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.infoq.com/presentations/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Imgur</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://imgur.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://imgur.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Heavy Music Archive</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.heavy-music.ru/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.heavy-music.ru/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Google+</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://plus.google.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://plus.google.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Freesound</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.freesound.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.freesound.org/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Flickr</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.flickr.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.flickr.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FC2 Video</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://video.fc2.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://video.fc2.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Facebook</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.facebook.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.facebook.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">eHow</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.ehow.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.ehow.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dailymotion</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.dailymotion.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.dailymotion.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CBS</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.cbs.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.cbs.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bandcamp</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://bandcamp.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://bandcamp.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AliveThai</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://alive.in.th/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://alive.in.th/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">interest.me</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://ch.interest.me/tvn\"><span style=\" text-decoration: underline; color:#0000ff;\">http://ch.interest.me/tvn</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">755<br />ナナゴーゴー</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://7gogo.jp/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://7gogo.jp/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">niconico<br />ニコニコ動画</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.nicovideo.jp/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.nicovideo.jp/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">163<br />网易视频<br />网易云音乐</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://v.163.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://v.163.com/</span></a><br /><a href=\"http://music.163.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://music.163.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">56网</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.56.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.56.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">AcFun</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.acfun.tv/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.acfun.tv/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Baidu<br />百度贴吧</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://tieba.baidu.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://tieba.baidu.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">爆米花网</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.baomihua.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.baomihua.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">bilibili<br />哔哩哔哩</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.bilibili.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.bilibili.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dilidili</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.dilidili.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.dilidili.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">豆瓣</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.douban.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.douban.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">凤凰视频</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://v.ifeng.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://v.ifeng.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">风行网</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.fun.tv/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.fun.tv/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">iQIYI<br />爱奇艺</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.iqiyi.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.iqiyi.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">激动网</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.joy.cn/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.joy.cn/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">酷6网</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.ku6.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.ku6.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">酷狗音乐</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.kugou.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.kugou.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">酷我音乐</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.kuwo.cn/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.kuwo.cn/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">乐视网</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.le.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.le.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">荔枝FM</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.lizhi.fm/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.lizhi.fm/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">秒拍</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.miaopai.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.miaopai.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MioMio弹幕网</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.miomio.tv/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.miomio.tv/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">痞客邦</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.pixnet.net/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.pixnet.net/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PPTV聚力</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.pptv.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.pptv.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">齐鲁网</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://v.iqilu.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://v.iqilu.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">QQ<br />腾讯视频</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://v.qq.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://v.qq.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">阡陌视频</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://qianmo.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://qianmo.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">THVideo</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://thvideo.tv/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://thvideo.tv/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sina<br />新浪视频<br />微博秒拍视频</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://video.sina.com.cn/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://video.sina.com.cn/</span></a><br /><a href=\"http://video.weibo.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://video.weibo.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sohu<br />搜狐视频</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://tv.sohu.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://tv.sohu.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">天天动听</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.dongting.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.dongting.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Tudou<br />土豆</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.tudou.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.tudou.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">虾米</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.xiami.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.xiami.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">阳光卫视</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.isuntv.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.isuntv.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">音悦Tai</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.yinyuetai.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.yinyuetai.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Youku<br />优酷</span></p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.youku.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.youku.com/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">央视网</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.cntv.cn/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.cntv.cn/</span></a></p></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td>\n"
                                               "<td></td></tr>\n"
                                               "<tr>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">花瓣</p></td>\n"
                                               "<td>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://huaban.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://huaban.com/</span></a></p></td>\n"
                                               "<td></td>\n"
                                               "<td>\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✓</p></td>\n"
                                               "<td></td></tr></table></body></html>"))
        self.menu_settings.setTitle(_translate("MainWindow", "Settings"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.action_file_path.setText(_translate("MainWindow", "File path"))
        self.action_check_for_updates.setText(_translate("MainWindow", "Check for updates"))
        self.action_report_bugs.setText(_translate("MainWindow", "Report bugs"))
        self.action_about.setText(_translate("MainWindow", "About"))

    def set_slot(self):
        self.button_download.clicked.connect(self.get_info)

    def get_info(self):
        urls = (str(self.urls_text_edit.toPlainText())).split(';')
        mlog.debug(urls[0])
        self.m_thread = GetVideoInfoThread(urls, **kwargs)
        self.m_thread.finish_signal.connect(self.finish_get_info)
        self.m_thread.start()

    def finish_get_info(self, ls ,can_download):
        for item in ls:
            mlog.debug(item)
        mlog.debug(__name__ + 'finish_get_info: '+str(can_download))
